### ISSUE TITLE
Error on using  service grocy.consume_product_from_stock

### ISSUE THREAD

**Issue by renarena** [custom-components/grocy#105]
**Describe the bug**
use developer tools to call service: grocy.consume_product_from_stock
  service_data:
    product_id: 1
    amount: 5
    transaction_type: CONSUME

If there are less then 5 in stock, this throws an error 400.
Same occurs if i try to execute an not existing chore.

**Expected behavior**
some sort of error handling/info to user?
Not sure how errors have to be handled in such cases.

**To Reproduce**
select grocy service on developer tools
click on example data
change value to something not existing
execute

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant Home, 0.115.6
Grocy Home Assistant addon: 0.9.1 with Grocy, 2.7.1
grocy custom component: 2.0.2

**How do you have Grocy installed? Add-on or external?**
addon
**Have you added debugging to the log, and what does the log say?**
```
2020-10-02 17:28:42 ERROR (MainThread) [custom_components.grocy] Update of Shopping_list failed with 400 Client Error: Bad Request for url: http://192.168.1.222:9192/api/stock/products/4
2020-10-02 17:28:42 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 4.347 seconds
2020-10-02 17:28:59 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for grocy doing I/O at custom_components/grocy/services.py, line 176: coordinator.api.consume_product(
2020-10-02 17:28:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2948033264] 400 Client Error: Bad Request for url: http://192.168.1.222:9192/api/stock/products/77/consume
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/grocy/services.py", line 96, in async_call_grocy_service
    await async_consume_product_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 176, in async_consume_product_service
    coordinator.api.consume_product(
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 547, in consume_product
    return self._api_client.consume_product(
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 585, in consume_product
    self._do_post_request(f"stock/products/{product_id}/consume", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 494, in _do_post_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.1.222:9192/api/stock/products/77/consume
2020-10-02 17:29:15 ERROR (MainThread) [custom_components.grocy] Update of Shopping_list failed with 400 Client Error: Bad Request for url: http://192.168.1.222:9192/api/stock/products/4
2020-10-02 17:29:16 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 4.157 seconds
```

**Additional context**
FF developer console says:
Uncaught (in promise) 
Object { code: "unknown_error", message: "400 Client Error: Bad Request for url: http://192.168.1.222:9192/api/stock/products/77/consume" }
app.4ab9da5a.js:40840
    callService app.4ab9da5a.js:40840
    AsyncFunctionThrow self-hosted:697

**Comment by isabellaalstrom** [comment]
The error codes come from the library, and that in it's turn gets the error message from the api. I cannot fix this from the component.

**Comment by renarena** [comment]
If its an auth problem, how can i find out?

**Comment by isabellaalstrom** [comment]
It's not an auth problem if the problem is that you are trying to consume more than you have. That's expected not to work.
