### ISSUE TITLE
Error when trying to track chores

### ISSUE THREAD

**Issue by olavbolav** [custom-components/grocy#121]
**Describe the bug**
Get an error in Home assistant when trying to track a chore. I have tried to track it from the custom chores card in lovelace and using the service call execute_chores in dev tools. The error I get is the same.

**Expected behavior**
Expected the chore to get tracked and updated in grocy. Just get an error, nothing gets tracked in Grocy.

**To Reproduce**
1. Try to track a chore using the chore card or execute_chores.

**What is your installed versions of Home Assistant, Grocy and this integration?**
HA: 2021.4.0
Grocy: 3.0.1 (add-on: 0.12.0)
Integration: 3.0.1
**How do you have Grocy installed? Add-on or external?**
Add-on
**Have you added debugging to the log, and what does the log say?**
````
2021-04-08 12:40:38 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.646 seconds
2021-04-08 12:41:10 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.726 seconds
2021-04-08 12:41:46 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 6.622 seconds
2021-04-08 12:42:18 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.654 seconds
2021-04-08 12:42:50 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.801 seconds
2021-04-08 12:43:22 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.685 seconds
2021-04-08 12:43:54 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.699 seconds
2021-04-08 12:44:26 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.746 seconds
2021-04-08 12:44:58 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.758 seconds
2021-04-08 12:45:30 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.813 seconds
2021-04-08 12:46:02 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.662 seconds
2021-04-08 12:46:34 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.923 seconds
2021-04-08 12:47:06 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.796 seconds
2021-04-08 12:47:41 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 5.783 seconds
2021-04-08 12:48:13 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.678 seconds
2021-04-08 12:48:45 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.682 seconds
2021-04-08 12:49:17 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.692 seconds
2021-04-08 12:49:49 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.669 seconds
2021-04-08 12:50:21 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.680 seconds
2021-04-08 12:50:53 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.710 seconds
2021-04-08 12:51:24 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for grocy doing I/O at custom_components/grocy/services.py, line 191: coordinator.api.execute_chore(chore_id, done_by, tracked_time)
2021-04-08 12:51:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1740171176] I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/grocy/services.py, line 191: coordinator.api.execute_chore(chore_id, done_by, tracked_time)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/grocy/services.py", line 99, in async_call_grocy_service
await async_execute_chore_service(hass, coordinator, service_data)
File "/config/custom_components/grocy/services.py", line 191, in async_execute_chore_service
coordinator.api.execute_chore(chore_id, done_by, tracked_time)
File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 98, in execute_chore
return self._api_client.execute_chore(chore_id, done_by, tracked_time)
File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 617, in execute_chore
return self._do_post_request(f"chores/{chore_id}/execute", data)
File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 557, in _do_post_request
resp = requests.post(
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/grocy/services.py, line 191: coordinator.api.execute_chore(chore_id, done_by, tracked_time)
2021-04-08 12:51:25 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.657 seconds
````

**Comment by isabellaalstrom** [comment]
I noticed too. I will try to fix this as soon as I can, but right now I have some family things that unfortunately makes me not being able to do this right at this moment.

**Comment by ludeeus** [comment]
<https://developers.home-assistant.io/docs/asyncio_working_with_async#calling-sync-functions-from-async>

**Comment by isabellaalstrom** [comment]
@olavbolav Could you please try the latest beta?

**Comment by cyberfly79** [comment]
Thanks, it works!

**Comment by olavbolav** [comment]
> @olavbolav Could you please try the latest beta?

Thanks!  Working when i hit track in the custom chores card. Also working from service_call, but wathever I put in tracked_time, the current time gets logged instead. Not sure if there is something wrong with how I write my service_call, but I have tried putting in the datetime in different ways.

```
service: grocy.execute_chore
data: {
  "chore_id":11,
  "tracked_time":"2021-04-13T16:00:00.251Z",
  "done_by":1
}

```
In the example above, the current time is logged, not tracked_time.

```
2021-04-13 16:57:06 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.663 seconds
2021-04-13 16:57:38 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.657 seconds
2021-04-13 16:57:57 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2021-04-13 16:57:57 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2021-04-13 16:57:59 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 2.633 seconds
```

**Comment by ludeeus** [comment]
The log will always have the time of the log entry, that applies to everything, not just these service calls

**Comment by olavbolav** [comment]
Sorry, bad explaining from my part Ludeeus. I don't mean in the HA logger, but the time that gets logged as "last tracked" in grocy. If I have understand it correctly, it should be possible to set the time for when the chore was executed by using "tracked_time"?

**Comment by ludeeus** [comment]
I'm not sure (as I don't use this at all) But open a new issue for that since that's not really related to this issue.
