### ISSUE TITLE
Get this issues after pushing track on custom chores card

### ISSUE THREAD

**Issue by adtwomey** [custom-components/grocy#133]
Get this issues after pushing track.

Use Home Assistant Core 2021.4.4
Grocy custom component 3.0.5
Grocy Docker Version 3.0.1
Lovelace Grocy Chores Card 2.1.0

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service await hass.services.async_call( File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call task.result() File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service await handler.job.target(service_call) File "/config/custom_components/grocy/services.py", line 105, in async_call_grocy_service await async_execute_chore_service(hass, coordinator, service_data) File "/config/custom_components/grocy/services.py", line 207, in async_execute_chore_service await hass.async_add_executor_job(wrapper) File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/grocy/services.py", line 205, in wrapper coordinator.api.execute_chore(chore_id, done_by, tracked_time) File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 107, in execute_chore return self._api_client.execute_chore(chore_id, done_by, tracked_time) File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 633, in execute_chore return self._do_post_request(f"chores/{chore_id}/execute", data) File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 565, in _do_post_request raise GrocyError(resp) pygrocy.errors.grocy_error.GrocyError: <Response

**Comment by isabellaalstrom** [comment]
Are you trying to track with another user id than the one who created the api key?

**Comment by adtwomey** [comment]
> Are you trying to track with another user id than the one who created the api key?

Have try with one user have not worked. Have realy to forum last night. With pictures...

**Comment by adtwomey** [comment]
Also I use home assistant cloud if this does any think different...

**Comment by isabellaalstrom** [comment]
Cloud should not make a difference.
Try calling this in your browser: http://192.168.0.16:9192/api/users and see what id the user has

**Comment by isabellaalstrom** [comment]
I have added instructions in the readme. Try these and get back to me. https://github.com/isabellaalstrom/lovelace-grocy-chores-card#user_id

**Comment by adtwomey** [comment]
![20210428_190451](https://user-images.githubusercontent.com/14849762/116378223-45b35800-a855-11eb-9baf-0551d08e88ff.jpg)
I am user ID no. 2... Have change card to suit and now working... Thanks... P.S  is there a way to press the track button in a Automations as an Actions.... It's going to be for an notification to the Android app....

**Comment by isabellaalstrom** [comment]
Use the service call, like this:
```
service: grocy.execute_chore
data:
  chore_id: 1
  done_by: 2
```
Chore id you can get from the entity attributes and done by is your user id.
