### ISSUE TITLE
Can't add generic (tasks)

### ISSUE THREAD

**Issue by isabellaalstrom** [custom-components/grocy#139]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
Service Add generic doesn't add task

**Expected behavior**
Adding task

**To Reproduce**
```

data:
  data:
    due_date: '{{ now().date() }}'
    name: test med template
  entity_type: tasks
service: grocy.add_generic


```

**Have you added debugging to the log, and what does the log say?**
```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/grocy/services.py:239
Integration: Grocy (documentation)
First occurred: 8:54:09 AM (1 occurrences)
Last logged: 8:54:09 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/grocy/services.py", line 111, in async_call_grocy_service
    await async_add_generic_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 241, in async_add_generic_service
    await hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/services.py", line 239, in wrapper
    coordinator.api.add_generic(entity_type, data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 216, in add_generic
    return self._api_client.add_generic(entity_type.value, data)
AttributeError: 'str' object has no attribute 'value'

```

**Additional context**

**Comment by SebRut** [comment]
This is happening because `add_generic` expects an [`EntityType`](https://sebrut.github.io/pygrocy/data_models/generic.html#pygrocy.data_models.generic.EntityType) instead of a string. Something like this should work:
```python
type_str = "locations"
type = EntityType(type_str)
grocy.add_generic(type, {})
```

**Comment by isabellaalstrom** [comment]
@SebRut Yeah I figured it was supposed to be kind of like this with TransactionType? Will try this today. https://github.com/custom-components/grocy/blob/master/custom_components/grocy/services.py#L174
