### ISSUE TITLE
Error when retrieving Tasks: "TypeError: Object of type date is not JSON serializable"

### ISSUE THREAD

**Issue by karwosts** [custom-components/grocy#185]
## Unless all relevant information is provided, I can't help you

**Describe the bug**
I use both Chores and Tasks in Grocy. Grocy integration fetches chores data correctly and correctly updates sensor.grocy_chores.

However sensor.grocy_tasks is always "unknown". I see the following repeated over and over in the log:
```
2022-02-14 11:32:26 DEBUG (MainThread) [custom_components.grocy.sensor] Data for sensor.grocy_chores: [<pygrocy.data_models.chore.Chore object at 0x7f9f1a8d1c70>]
2022-02-14 11:32:26 DEBUG (MainThread) [custom_components.grocy.sensor] Data for sensor.grocy_tasks: [<pygrocy.data_models.task.Task object at 0x7f9f1a88c8e0>]
2022-02-14 11:32:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _async_write_ha_state
self.device_state_attributes is not None
File "/config/custom_components/grocy/entity.py", line 143, in device_state_attributes
return json.loads(json.dumps(data, cls=GrocyJSONEncoder))
File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
return cls(
File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/config/custom_components/grocy/json_encode.py", line 26, in default
return json.JSONEncoder.default(self, o)
File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
2022-02-14 11:32:56 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 0.301 seconds (success: True)
```

Also found and added pygrocy debug message for tasks:

```
022-02-15 10:00:12 DEBUG (SyncWorker_0) [pygrocy.grocy_api_client] --> GET /tasks
2022-02-15 10:00:12 DEBUG (SyncWorker_0) [pygrocy.grocy_api_client] <-- 200 for /tasks
2022-02-15 10:00:12 DEBUG (SyncWorker_0) [pygrocy.grocy_api_client] b'[{"id":"1","name":"Finish Wine Fermentation","description":"text","due_date":"2022-02-27","done":"0","done_timestamp":null,"category_id":"1","assigned_to_user_id":"1","row_created_timestamp":"2022-02-14 11:24:35","assigned_to_user":{"id":"1","username":"admin","first_name":null,"last_name":null,"row_created_timestamp":"2022-02-04 08:50:28","display_name":"admin","picture_file_name":null},"category":{"id":"1","name":"Winemaking","description":"","row_created_timestamp":"2022-02-14 11:26:31"}}]'
2022-02-15 10:00:12 DEBUG (MainThread) [custom_components.grocy] Finished fetching grocy data in 0.474 seconds (success: True)
```

### General information to help debugging:
**What sensors do you have enabled? Are they working and/or what state are they in? Do you have the corresponding functions enabled in Grocy?**
I only have one task in the grocy task list, as follows:

![image](https://user-images.githubusercontent.com/32912880/154119230-9febbbc0-c519-4459-8829-a47867508dd3.png)

**What is your installed versions of Home Assistant, Grocy and this integration?**
HAOS core-2021.12.8
Grocy 3.1.3
Custom component v4.1.0

**How do you have Grocy installed? Add-on or external?**
Add-on

**Comment by karwosts** [comment]
Not a python expert, but I just guessed at a fix and it seemed to have worked for me, the tasks are correctly retrieved now. I created a pull request, but I'm very inexperienced with github, so if I clicked on something wrong and did something stupid, I apologize in advance :)
