### ISSUE TITLE
Configuration Help

### ISSUE THREAD

**Issue by DeBelsch** [custom-components/grocy#24]
Hello, 
I need help with the configuration. I couldn´t find a forum, so i´m asking here. 

I followed the Readme installation, but I´m not sure what the API url is. I tried some but i couldn´t get it to connect.
I installed the grocy addon on Hassio and it works. The network interface of the addon is untouched.

Here is the (for my understanding) most plausible configuration:

grocy:
  url: "https://xxxxxx.duckdns.org:8123/a0d7b954_grocy"
  api_key: "**xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**"
  verify_ssl: true
  port: 9192
  sensor:
    - enabled: true
  binary_sensor:
    - enabled : true

And here are the logs:

`Log Details (ERROR)
Wed Nov 13 2019 12:37:29 GMT+0100 (Mitteleuropäische Normalzeit)
grocy: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x71dcfb30>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='**xxxxxx**.duckdns.org', port=8123): Max retries exceeded with url: /a0d7b954_grocy:9192/api/stock/volatile (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x71dcfb30>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/grocy/binary_sensor.py", line 33, in async_update
    await self._client.async_update_expiring_products()
  File "/config/custom_components/grocy/__init__.py", line 199, in async_update_expiring_products
    self.client.expiring_products))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 161, in expiring_products
    raw_expiring_product = self.volatile_stock().expiring_products
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 158, in volatile_stock
    return self._api_client.get_volatile_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 312, in get_volatile_stock
    resp = requests.get(req_url, verify=self._verify_ssl, headers=self._headers)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='**xxxxxx**.duckdns.org', port=8123): Max retries exceeded with url: /a0d7b954_grocy:9192/api/stock/volatile (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x71dcfb30>: Failed to establish a new connection: [Errno 111] Connection refused'))`

I know there had been other issues for the configuration setup, but either they said they solved it without an explanation or they got redirected to another issue. I read all the issues, but my knowledge is not good enough to understand most of it.

I would be really happy about some help. 
Thanks

**Comment by r1kkie** [comment]
Have you tried to use your local adress for your hassio, and comment out the ssl setting? Under url just type the ip adress and skip the rest.

This is my config:
```

grocy:
  url: http://192.168.1.70
  api_key: ******
  port: 9192
  sensor:
    - enabled: true
```

**Comment by Gruzzen** [comment]
The code example has it listed as https://URL

Changing it to http://URL removed the above errors from my install.  It also matches the config from r1kkie.
