### ISSUE TITLE
Unable to load chore sensor

### ISSUE THREAD

**Issue by Gibby** [custom-components/grocy#26]
**Describe the bug**
2019-11-20 22:26:02 ERROR (MainThread) [homeassistant.components.sensor] grocy: Error on device update!          
Traceback (most recent call last):                                                                                           
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity          
    await entity.async_device_update(warning=False)                                                                          
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update                               
    await self.async_update()                                                                               
  File "/config/custom_components/grocy/sensor.py", line 88, in async_update                                                                                                                                
    await self.hass.data[DOMAIN_DATA]["client"].async_update_chores()                                                                                                                                       
  File "/config/custom_components/grocy/__init__.py", line 191, in async_update_chores                                        
    await self.hass.async_add_executor_job(self.client.chores, [True]))                                              
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run                                                    
    result = self.fn(*self.args, **self.kwargs)                                                                                    
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 199, in chores                                       
    raw_chores = self._api_client.get_chores()                                                                              
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 328, in get_chores                     
    return [CurrentChoreResponse(chore) for chore in parsed_json]                                                             
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 328, in <listcomp>                     
    return [CurrentChoreResponse(chore) for chore in parsed_json]                                                   
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 156, in __init__                         
    self._chore_id = parse_int(parsed_json.get('chore_id'), None)
AttributeError: 'str' object has no attribute 'get'

**Expected behavior**
Able to load chores

**Are you using HASSIO to run grocy?**
No

**configuration.yaml entry**
```
grocy:
  url: "http://xxxxxxxxx/api"
  api_key: !secret grocy_api_key
  verify_ssl: false
  port: 80
  sensor:
    - enabled: true
```

**Additional context**
Home Assistant version: 0.102.0
Grocy version: 2.5.2

Able to curl the api with no issues.

**Comment by SebRut** [comment]
Hey, are the other parts of the custom component like products working? Could you provide an example json response for the chores endpoint?

**Comment by Gibby** [comment]
@SebRut I only use chores.

Request:
`curl -v -X GET "http://x.x.x.x/api/chores" -H "accept: application/json" -H "GROCY-API-KEY: xxxxxxxxxxxx"`

Response:
`[
  {
    "chore_id": "4",
    "last_tracked_time": null,
    "next_estimated_execution_time": "2999-12-31 23:59:59",
    "track_date_only": "0",
    "next_execution_assigned_to_user_id": null
  }
]`

**Comment by SebRut** [comment]
Hmm...the response seems valid, are you running the curl command from the homeassistant host?

**Comment by Gibby** [comment]
Yep just tested using curl on the same host as home assistant and as the same user.

**Comment by SebRut** [comment]
I just checked the current doc for configuration and it seems that you dont need `/api` at the end of the url anymore. Could you try removing that part from your config?

**Comment by Gibby** [comment]
@SebRut that worked. Thanks!
