### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by benek984** [custom-components/grocy#274]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/62546477/236627644-bac8f2aa-5f03-4b9d-a2f1-63f516e5a230.png">

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/grocy/__init__.py:52
Integration: Grocy (documentation, issues)
First occurred: 14:32:15 (3 occurrences)
Last logged: 14:33:41

Error setting up entry Grocy for grocy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/grocy/__init__.py", line 52, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by karwosts** [comment]
If you update to core 2023.5, you need to update grocy component to v4.8.0. This was fixed in #260
