### ISSUE TITLE
Sensor could not update

### ISSUE THREAD

**Issue by diplix** [custom-components/grocy#3]
Home Assistant 0.95.0

i’m getting an error with this configuration:
```
grocy:
  #url: "http://localhost:8080/api/"
  #url: "http://tc.local:8080/api/"
  url: "http://192.168.1.70:8080/api/"
  api_key: "xxx"
  sensor:
    - enabled: true
```
i can see that the api is queried, grocy marks the api key as beeing used. 

```
2019-06-28 07:58:14 ERROR (MainThread) [custom_components.grocy] Could not update data - 'NoneType' object has no attribute 'split'
2019-06-28 07:58:14 ERROR (MainThread) [homeassistant.components.sensor] grocy: Error on device update!
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/grocy/sensor.py", line 31, in async_update
    stock = self.hass.data[DOMAIN_DATA]["stock"]
KeyError: 'stock'

```

pygrocy does work in the home-asssistant venv:

```
>>> from pygrocy import Grocy
>>> grocy = Grocy("http://localhost:8080/api/", "xxx")
>>> for entry in grocy.stock():
...     print("{} in stock for product id {}".format(entry.product_id, entry.available_amount))
... 
3 in stock for product id 1.0
7 in stock for product id 0.0
9 in stock for product id 1.0
11 in stock for product id 1.0
12 in stock for product id 0.0
13 in stock for product id 3.0
14 in stock for product id 2.0
15 in stock for product id 5.0
16 in stock for product id 3.0
17 in stock for product id 2.0
18 in stock for product id 1.0
19 in stock for product id 2.0
20 in stock for product id 1.0
21 in stock for product id 2.0
22 in stock for product id 2.0
23 in stock for product id 1.0
24 in stock for product id 1.0
25 in stock for product id 1.0
27 in stock for product id 2.0
28 in stock for product id 1.0
29 in stock for product id 1.0
```

**Comment by SebRut** [comment]
I'll look into this thank you for reporting.

**Comment by SebRut** [comment]
Could you try running your snippet from above with `get_details=True` as a parameter for stock. I guess the error is related to a product not having a (valid) barcode entry  as that's the only location in code where `split` is used.

**Comment by diplix** [comment]
oh, yes. hardly any of my products do have barcode entries. i’ll check it with get_details=True later, but i’m pretty sure that’s the reason for the error.

**Comment by SebRut** [comment]
Not having barcodes shouldn't be the reason for the errour thought as about half of my products don't have barcodes too.

**Comment by diplix** [comment]
```
>>> for entry in grocy.stock(get_details=True):
...     print("{} in stock for product id {}".format(entry.product_id, entry.available_amount))
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy.py", line 82, in stock
    item.get_details(self._api_client)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy.py", line 20, in get_details
    details = api_client.get_product(self.product_id)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy_api_client.py", line 222, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy_api_client.py", line 140, in __init__
    self._product = ProductData(parsed_json.get('product'))
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy_api_client.py", line 37, in __init__
    self._barcodes = parsed_json.get('barcode', "").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

```
>>> for entry in grocy.stock(get_details=True):
...     print("{} in stock for product id {}".format(entry.product_id, entry.amount))
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy.py", line 82, in stock
    item.get_details(self._api_client)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy.py", line 20, in get_details
    details = api_client.get_product(self.product_id)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy_api_client.py", line 222, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy_api_client.py", line 140, in __init__
    self._product = ProductData(parsed_json.get('product'))
  File "/home/homeassistant/homeassistant/lib/python3.6/site-packages/pygrocy/grocy_api_client.py", line 37, in __init__
    self._barcodes = parsed_json.get('barcode', "").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by diplix** [comment]
if it helps, barcode is indeed null/none:
`[{"id":"3","name":"Milch","description":"Vollmilch, fettreduziert","location_id":"2","qu_id_purchase":"3","qu_id_stock":"3","qu_factor_purchase_to_stock":"1.0","barcode":null,"min_stock_amount":"1","default_best_before_days":"14","row_created_timestamp":"2019-06-27 13:39:46","product_group_id":"6","picture_file_name":null,"default_best_before_days_after_open":"7","allow_partial_units_in_stock":"0","enable_tare_weight_handling":"0","tare_weight":"0.0","not_check_stock_fulfillment_for_recipes":"0"}]`

**Comment by diplix** [comment]
there’s another thing: i tried to save a couple of barcodes (grocy latest release, fresh install) but all my products do have `barcode: null` data. so my grocy does not seem to save the barcode data. may be i’m entering it in a wrong format?

**Comment by Spankythemusical** [comment]
I'm not trying to hijack this thread, but I have the exact same issue as diplix.  
Alongside that issue, I also have these 2 errors (I don't know if diplix also sees these):
`2019-06-28 12:30:41 CRITICAL (MainThread) [custom_components.grocy] OrderedDict([('enabled', True), ('name', 'grocy')])`
`2019-06-28 12:30:59 ERROR (MainThread) [custom_components.grocy] Could not update data - Expecting value: line 1 column 1 (char 0)`
I only include these as maybe they'll assist in troubleshooting the issue.  The rest of my configs (with the exception of the IP and the Key) are the same and show the same.

**Comment by SebRut** [comment]
@Spankythemusical I also get that CRITICAL issue all the time (at startup I think) but haven't yet investigated it as it doesn't seem to cause any problems. That second error sounds interesting but is kinda hard to debug without more information.

**Comment by Spankythemusical** [comment]
@SebRut please let me know what additional information, if any, I can provide.  And thank you for working on this.

**Comment by SebRut** [comment]
@diplix Could you check version 0.1.1 I just published?

**Comment by SebRut** [comment]
@Spankythemusical Used python, homeassistant, component version could be interesting. Also additional log output for grocy (if existing) and a sample response from your grocy API instance. Also could we create a new issue for this to keep concerns separated?

**Comment by diplix** [comment]
```
2019-06-28 14:30:08 CRITICAL (MainThread) [custom_components.grocy] OrderedDict([('enabled', True), ('name', 'grocy')])
2019-06-28 14:30:28 ERROR (MainThread) [custom_components.grocy] Could not update data - 'NoneType' object has no attribute 'get'
2019-06-28 14:31:00 ERROR (MainThread) [custom_components.grocy] Could not update data - 'NoneType' object has no attribute 'get'
```

the platform initializes and the sensor is generated. however:

![Bildschirmfoto 2019-06-28 um 14 33 19](https://user-images.githubusercontent.com/4541494/60342430-b6676000-99b1-11e9-9ae0-2887f579f17c.png)

**Comment by diplix** [comment]
after the platform initialized, the service call `grocy.add_product` does work. so it’s only the sensor that’s still a little bumpy.

**Comment by SebRut** [comment]
Could you please run the following snippet using the latest pygrocy release? I guess some missing (?) data is messing up the parsing but HA log messages aren't really helping.

```python3
from pygrocy import Grocy
grocy = Grocy("http://192.168.x.xxx/api/", "XXXX")

print("Stock")
for entry in grocy.stock(get_details=True):
    print("{} - {}".format(entry.name, entry.available_amount))

print("Chores")
for entry in grocy.chores(get_details=True):
    print("{} - {}".format(entry.name, entry.last_tracked_time))
```

**Comment by diplix** [comment]
did not run the snippet above, but installed version v0.1.2 which seems to work flawlessly with HA 0,95.0. my sensor is now populates with a status of 21 products and json strings containing all product and  chore data.
