### ISSUE TITLE
Errors on not using products

### ISSUE THREAD

**Issue by isabellaalstrom** [custom-components/grocy#42]
**Describe the bug**
I removed stock from my grocy addon configuration, as I don't use them. Now the integration throws a lot of errors relating to products.

**To Reproduce**
1. change to `stock: false` in addon config
2. Restart home assistant
3. Check logs

**Are you using HASSIO to run grocy?**
Yes

**configuration.yaml entry**
```yaml
Your grocy component config entry
```

**Additional context**
```
2020-03-18 19:54:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 220, in async_update_expiring_products
    self.client.expiring_products, [True]))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 161, in expiring_products
    raw_expiring_product = self.volatile_stock().expiring_products
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 158, in volatile_stock
    return self._api_client.get_volatile_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 314, in get_volatile_stock
    return CurrentVolatilStockResponse(parsed_json)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 199, in __init__
    self._expiring_products = [CurrentStockResponse(product) for product in parsed_json.get('expiring_products')]
TypeError: 'NoneType' object is not iterable
```

**Comment by SebRut** [comment]
Hi, this seems like a bug in pygrocy. Unfortunately I dont have time to investigate this, but maybe @BlueBlueBlob could check if this is fixed in newer versions.

**Comment by BlueBlueBlob** [comment]
Checking 👍

**Comment by BlueBlueBlob** [comment]
Ok with new pygrocy version, it raises HttpError.
So we will be able to add a try/except in custom component.
Need a pygrocy release :)

**Comment by SebRut** [comment]
TY for checking so quickly :)

I released 0.14.0 of pygrocy like an hour ago, so that version should include the latest changes.

**Comment by BlueBlueBlob** [comment]
Ok I can work for a fix here :)
Keep in touch, PR incoming ;)

**Comment by BlueBlueBlob** [comment]
@isabellaalstrom I cannot test with stock disable on my Hassio.
If I provide you a test version, can you test it please ?

**Comment by BlueBlueBlob** [comment]
https://github.com/BlueBlueBlob/grocy/tree/fix/custom_components

**Comment by isabellaalstrom** [comment]
Sure, I'll do it in a bit

**Comment by BlueBlueBlob** [comment]
> Sure, I'll do it in a bit

Thanks 👍
Reminder, just in case : delete integration, delete Grocy custom component folder, copy the test one and restart HA. It will take time before having integration window appear because of pygrocy update.

Good luck :)

**Comment by isabellaalstrom** [comment]
I'm getting "unknown error occurred" when I'm trying to add the test integration now.

**Comment by isabellaalstrom** [comment]
```
2020-03-19 11:43:35 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/grocy/config_flow.py", line 89, in _test_credentials
    client.stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 164, in stock
    raw_stock = self._api_client.get_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 366, in get_stock
    parsed_json = self._do_get_request("stock")
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 334, in _do_get_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.78:9192/api/stock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/grocy/config_flow.py", line 35, in async_step_user
    user_input["port"],user_input["verify_ssl"]
  File "/config/custom_components/grocy/config_flow.py", line 92, in _test_credentials
    _LOGGER.exception(e)
NameError: name '_LOGGER' is not defined
2020-03-19 11:43:59 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/grocy/config_flow.py", line 89, in _test_credentials
    client.stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 164, in stock
    raw_stock = self._api_client.get_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 366, in get_stock
    parsed_json = self._do_get_request("stock")
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 334, in _do_get_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.78:9192/api/stock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/grocy/config_flow.py", line 35, in async_step_user
    user_input["port"],user_input["verify_ssl"]
  File "/config/custom_components/grocy/config_flow.py", line 92, in _test_credentials
    _LOGGER.exception(e)
NameError: name '_LOGGER' is not defined
2020-03-19 11:44:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/grocy/config_flow.py", line 89, in _test_credentials
    client.stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 164, in stock
    raw_stock = self._api_client.get_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 366, in get_stock
    parsed_json = self._do_get_request("stock")
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 334, in _do_get_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.78:9192/api/stock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/grocy/config_flow.py", line 35, in async_step_user
    user_input["port"],user_input["verify_ssl"]
  File "/config/custom_components/grocy/config_flow.py", line 92, in _test_credentials
    _LOGGER.exception(e)
NameError: name '_LOGGER' is not defined
2020-03-19 11:44:35 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/grocy/config_flow.py", line 89, in _test_credentials
    client.stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 164, in stock
    raw_stock = self._api_client.get_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 366, in get_stock
    parsed_json = self._do_get_request("stock")
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 334, in _do_get_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.78:9192/api/stock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/grocy/config_flow.py", line 35, in async_step_user
    user_input["port"],user_input["verify_ssl"]
  File "/config/custom_components/grocy/config_flow.py", line 92, in _test_credentials
    _LOGGER.exception(e)
NameError: name '_LOGGER' is not defined
```

**Comment by BlueBlueBlob** [comment]
Thx I forget this part.
Fixing.
Thx again for providing log 👍

**Comment by BlueBlueBlob** [comment]
Update

**Comment by isabellaalstrom** [comment]
I just need to replace that file?

**Comment by isabellaalstrom** [comment]
I replaced it, but I had to reboot. Then it worked! Still got the entity shopping list though.

**Comment by BlueBlueBlob** [comment]
> I replaced it, but I had to reboot. Then it worked! Still got the entity sensor.grocy_shopping_list though.

Thx ! 
If you didn't disable shopping list, I can't check more. Disable stock does not disable shopping list (Grocy behavior). Maybe you should disable shopping list too.
Can you check log to see if you have some warning about it ?

Thanks again for your feedback and time.
I will do a PR after your report.

Regards

**Comment by isabellaalstrom** [comment]
```
features:
  batteries: false
  calendar: false
  chores: true
  equipment: false
  recipes: false
  shoppinglist: false
  stock: false
  tasks: false
```

**Comment by isabellaalstrom** [comment]
No error in logs

**Comment by BlueBlueBlob** [comment]
Thx @isabellaalstrom .
I need more time for sensors. But you can disable it in lastest HA version.

Sorry to ask you and take time to answer : do you have product services ?

Thx for your time 👍

**Comment by BlueBlueBlob** [comment]
@SebRut can you release pygrocy with my last fix.
Or this PR will break product details... Sorry

**Comment by isabellaalstrom** [comment]
I only have grocy execute chore service, but it complains about my chore I'd when I execute from my card. That's new.

**Comment by BlueBlueBlob** [comment]
> I only have grocy execute chore service, but it complains about my chore I'd when I execute from my card. That's new.

I didn't change anything in chores service, so I guess it's about pygrocy update.

Can you provide log please ?

Thanks again for testing 👍

**Comment by isabellaalstrom** [comment]
I changed something in the card yesterday I just realized. Might be that. Will test more once by the computer.

**Comment by BlueBlueBlob** [comment]
> I changed something in the card yesterday I just realized. Might be that. Will test more once by the computer.

Thx, and btw your card rox ;)

**Comment by isabellaalstrom** [comment]
I think something changed with the sensor, what's in "items". It was `_chore_id` before, now it's `_id`.
As I fixed that it no longer complains about the id being wrong. However something also have changed in how it wants the formatted date and time in the service call. I tried calling the service from dev tools and it doesn't work with the example yaml anymore either.

This is the error I'm getting:
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in _execute_service
    handler.func(service_call)
  File "/config/custom_components/grocy/__init__.py", line 168, in handle_execute_chore
    grocy.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 213, in execute_chore
    return self._api_client.execute_chore(chore_id, done_by, tracked_time)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 393, in execute_chore
    localized_tracked_time = local_tz.localize(tracked_time)
  File "/usr/local/lib/python3.7/site-packages/pytz/tzinfo.py", line 318, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)

**Comment by isabellaalstrom** [comment]
Okey, I looked at the code and saw that date is no longer needed to send at all (maybe never was?) so I just removed it and it works.
