### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Dinth** [custom-components/grocy#46]
**Describe the bug**
I have added and configured the component, i havent even started using it yet, but the logs are showing a lot of errors

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 228, in async_update_expired_products
    self.client.expired_products, [True]))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 179, in expired_products
    item.get_details(self._api_client)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 24, in get_details
    details = api_client.get_product(self.product_id)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 322, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 231, in __init__
    self._location = LocationData(parsed_json.get('location'))
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 52, in __init__
    self._id = parse_int(parsed_json.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
```

```
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 198, in async_update_stock
    await self.hass.async_add_executor_job(self.client.stock, [True]))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 154, in stock
    item.get_details(self._api_client)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 24, in get_details
    details = api_client.get_product(self.product_id)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 322, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 231, in __init__
    self._location = LocationData(parsed_json.get('location'))
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 52, in __init__
    self._id = parse_int(parsed_json.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
```

**To Reproduce**
1. Install Grocy component through HACS
2. Add and configure it in integrations menu.

**Are you using HASSIO to run grocy?**
No

**configuration.yaml entry**
Component set up through GUI

**Additional context**

**Comment by Dinth** [comment]
Just to add a couple of things:
1. Chores sensor is showing all chores.
2. Expired and expiring products binary sensors are at "Off" state, but such products exist.
3. Stock sensor is at "unknown" state.

**Comment by SebRut** [comment]
Sounds like some products do not have a location assigned to them, could you check that?

**Comment by Dinth** [comment]
Indeed, but im not sure how this happened. I was definetely filling in location for all products i have entered. Anyhow, i believe it is fixed for me.
