### ISSUE TITLE
0.4.0 integration adds fine but no sensors

### ISSUE THREAD

**Issue by VinistoisR** [custom-components/grocy#55]
1. Add via HACS
2. Restart HA
3. HA Integrations --> add https://grocy.mydomain.net with port 443 --> adds with no errors
4. Restart HA

Result is no entities related to Grocy are present.  Services calls are available. 

I tried again with https://grocy.mydomain.net/api   (the setup hints to add your api url, but the example url shown does not have the /api path, this is confusing btw)

my Grocy install is available from everywhere at https://grocy.mydomain.net

in the HA log I'm getting:

```

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update,
    await self.async_update(),
  File "/config/custom_components/grocy/sensor.py", line 37, in async_update,
    await self.hass.data[DOMAIN_DATA]["client"].async_update_data(self.sensor_type),
    db_changed = await self.hass.async_add_executor_job(self.client.get_last_db_changed),
  File "/config/custom_components/grocy/__init__.py", line 186, in async_update_data,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run,
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 259, in get_last_db_changed,
    last_change_timestamp = parse_date(resp.json().get('changed_time')),
    result = self.fn(*self.args, **self.kwargs),
    return self._api_client.get_last_db_changed(),
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 453, in get_last_db_changed,
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json,
    return complexjson.loads(self.text, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads,
    return _default_decoder.decode(s),
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode,
    obj, end = self.raw_decode(s),
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode,
    await entity.async_device_update(warning=False),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity,
Traceback (most recent call last):,
2020-06-06 19:22:01 ERROR (MainThread) [homeassistant.components.sensor] grocy: Error on device update!,

```

**Comment by sweetgman** [comment]
Same issue with me except I used IP and port 9192 as instructed

**Comment by SebRut** [comment]
_Hey! Just wanted to let you know that I finally accepted, that I'll not be able to maintain this project for the foreseeable future. I'd be happy to hand most of this over to someone willing to work on this integration and will try to support this by working on SebRut/pygrocy._

**Comment by isabellaalstrom** [comment]
Hi! I will try to take over this component. Can you please try to download the pre-release that became available yesterday and see if that helps?

**Comment by isabellaalstrom** [comment]
Beta for 2.0 is out. I would be very happy if you could download it and check if the issue persists, and also if everything else is still working as expected. To download a beta via Hacs, if you haven't before, press the tre dots at the integration and choose reinstall, then you can choose to show beta releases.
