### ISSUE TITLE
Chores disabled in Grocy make whole integration to not work

### ISSUE THREAD

**Issue by tikismoke** [custom-components/grocy#77]
**Describe the bug**
In grocy data/config.php i disabled chores as i don't used them

**To Reproduce**
1. Disable chores in grocy config
2. try the integration

**Expected behavior**
Should only make chores not available but stock working for example.

**Are you using HASSIO to run grocy?**
No

**Comment by noxhirsch** [comment]
I have a similar problem, because I disabled many features in Grocy:
```
# Feature flags
Setting('FEATURE_FLAG_STOCK', true);
Setting('FEATURE_FLAG_SHOPPINGLIST', true);
Setting('FEATURE_FLAG_RECIPES', false);
Setting('FEATURE_FLAG_CHORES', false);
Setting('FEATURE_FLAG_TASKS', false);
Setting('FEATURE_FLAG_BATTERIES', false);
Setting('FEATURE_FLAG_EQUIPMENT', false);
Setting('FEATURE_FLAG_CALENDAR', false);

# Sub feature flags
Setting('FEATURE_FLAG_STOCK_PRICE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_LOCATION_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_PRODUCT_OPENED_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_PRODUCT_FREEZING', false);
Setting('FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS', false);
Setting('FEATURE_FLAG_CHORES_ASSIGNMENTS', false);
```
Home Assistant Log:
```
2020-08-16 22:47:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 227, in async_update_chores
    ] = await self.hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/__init__.py", line 223, in wrapper
    return self.client.chores(True)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 472, in chores
    raw_chores = self._api_client.get_chores()
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 489, in get_chores
    parsed_json = self._do_get_request("chores")
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 443, in _do_get_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://127.0.0.1:5555/api/chores
2020-08-16 22:47:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 237, in async_update_shopping_list
    ] = await self.hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/__init__.py", line 233, in wrapper
    return self.client.shopping_list(True)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 521, in shopping_list
    item.get_details(self._api_client)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 131, in get_details
    self._product = api_client.get_product(self._product_id).product
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 484, in get_product
    parsed_json = self._do_get_request(url)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 443, in _do_get_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://127.0.0.1:5555/api/stock/products/3
2020-08-16 22:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 270, in async_update_missing_products
    ] = await self.hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/__init__.py", line 266, in wrapper
    return self.client.missing_products(True)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 463, in missing_products
    item.get_details(self._api_client)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 63, in get_details
    details = api_client.get_product(self.id)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 486, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 332, in __init__
    self._location = LocationData(parsed_json.get('location'))
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 124, in __init__
    self._id = parse_int(parsed_json.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
2020-08-16 22:48:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/grocy/__init__.py", line 259, in async_update_expired_products
    ] = await self.hass.async_add_executor_job(wrapper)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/grocy/__init__.py", line 255, in wrapper
    return self.client.expired_products(True)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 454, in expired_products
    item.get_details(self._api_client)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 63, in get_details
    details = api_client.get_product(self.id)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 486, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 332, in __init__
    self._location = LocationData(parsed_json.get('location'))
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 124, in __init__
    self._id = parse_int(parsed_json.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
```

The stock sensor is working for me, but not the missing_products sensor.
I'm also running Grocy solo in Docker - not in HASSIO.

**Comment by tikismoke** [comment]
Using custom settings like you, only stock recipe and shopping list.

But nothing appears in ha until I re-enable everything, I didn't try to search Wich one is making this issue, i only re-enable everything to make test.

Grocy run in a dedicated lxc container no docker, same for ha (but in kvm/qemu python venv environment)

**Comment by isabellaalstrom** [comment]
I am working on config choices for disabling certain sensors. Until that it ready the workaround is to have all enabled in Grocy.

**Comment by isabellaalstrom** [comment]
Beta for 2.0 is out. I would be very happy if you could download it and check if the issue persists, and also if everything else is still working as expected. To download a beta via Hacs, if you haven't before, press the tre dots at the integration and choose reinstall, then you can choose to show beta releases.
