### ISSUE TITLE
Unable to use grocy.add_generic 

### ISSUE THREAD

**Issue by denko81** [custom-components/grocy#96]
When I try to use grocy.add_generic with the example data, via the developer tools, I get following error. 

Logger: homeassistant.components.websocket_api.http.connection.1853223336
Source: custom_components/grocy/services.py:224
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 0:22:22 (2 occurrences)
Last logged: 0:22:29

400 Client Error: Bad Request for url: https://denisb.duckdns.org:9192/api/objects/tasks
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/grocy/services.py", line 112, in async_call_grocy_service
    await async_add_generic_service(hass, coordinator, service_data)
  File "/config/custom_components/grocy/services.py", line 224, in async_add_generic_service
    coordinator.api.add_generic(entity_type, data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 619, in add_generic
    return self._api_client.add_generic(entity_type, data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 669, in add_generic
    self._do_post_request(f"objects/{entity_type}", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 490, in _do_post_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://denisb.duckdns.org:9192/api/objects/tasks

**Comment by isabellaalstrom** [comment]
With beta 6 it is now working for me to create a new task with service add generic and the example data. Could you try and report back?

**Comment by isabellaalstrom** [comment]
This is working in automation:
```
service: grocy.add_generic
data:
  entity_type: tasks
  data:
    name: This is an example task

**Comment by isabellaalstrom** [comment]
And this
```
service: grocy.add_generic
data_template:
  entity_type: tasks
  data:
    name: Test med template
    due_date: '{{ now().date() }}'

**Comment by isabellaalstrom** [comment]
Remember that tasks has to have unique names.

**Comment by isabellaalstrom** [comment]
Fixed in beta
